#!/usr/bin/env python

import sys

import tornado.httpserver
import tornado.ioloop

from vaytrou.app import make_app

# TODO: import sys and add egg paths

if __name__ == "__main__":
    environ = {}
    application = make_app(environ, sys.argv[1:])
    http_server = tornado.httpserver.HTTPServer(application)
    http_server.listen(8888)
    try:
        loop = tornado.ioloop.IOLoop.instance()
        loop.start()
    except KeyboardInterrupt:
        print "Exiting."
    finally:
        loop.stop()
        application.index.close()

